# Generated by Django 2.2.6 on 2019-10-24 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backtrackapp', '0003_auto_20191024_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
