# Generated by Django 3.1.dev20191024131625 on 2019-11-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('D', 'Developer'), ('M', 'Manager')], default='D', max_length=1),
        ),
    ]
