# Generated by Django 2.2.6 on 2019-10-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtrackapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available',
        ),
        migrations.AlterField(
            model_name='productbacklogitem',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('C', 'Complete')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('C', 'Complete')], max_length=2),
        ),
    ]
