# Generated by Django 2.2.6 on 2019-11-06 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtrackapp.Project'),
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_team', models.ManyToManyField(related_name='devs', to=settings.AUTH_USER_MODEL)),
                ('product_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_owner', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtrackapp.Project')),
                ('scrum_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_master', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
