# Generated by Django 2.2.7 on 2019-11-20 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backtrackapp', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('C', 'Complete')], default='NS', max_length=2),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='teamName',
            field=models.CharField(default='New Project Team', max_length=256),
        ),
        migrations.AddField(
            model_name='sprint',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sprint',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('C', 'Complete')], default='NS', max_length=2),
        ),
        migrations.AddField(
            model_name='sprint',
            name='totalCapacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='avaliable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productbacklogitem',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('C', 'Complete')], default='NS', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='burndown',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('C', 'Complete')], default='NS', max_length=2),
        ),
    ]
