# Generated by Django 2.2.7 on 2019-11-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtrackapp', '0003_auto_20191120_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
