# Generated by Django 3.1.dev20191024131625 on 2019-11-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtrackapp', '0005_auto_20191122_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtrackapp.Project'),
        ),
    ]
